//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnSapXep.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int soLuongPhanTuMacDinh {
            get {
                return ((int)(this["soLuongPhanTuMacDinh"]));
            }
            set {
                this["soLuongPhanTuMacDinh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int khoangCachGiuaCacNode {
            get {
                return ((int)(this["khoangCachGiuaCacNode"]));
            }
            set {
                this["khoangCachGiuaCacNode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int kichCoNode {
            get {
                return ((int)(this["kichCoNode"]));
            }
            set {
                this["kichCoNode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color mauNodeHoanTatSapXep {
            get {
                return ((global::System.Drawing.Color)(this["mauNodeHoanTatSapXep"]));
            }
            set {
                this["mauNodeHoanTatSapXep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color mauNenNode {
            get {
                return ((global::System.Drawing.Color)(this["mauNenNode"]));
            }
            set {
                this["mauNenNode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color mauNodeDangSapXep {
            get {
                return ((global::System.Drawing.Color)(this["mauNodeDangSapXep"]));
            }
            set {
                this["mauNodeDangSapXep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman, 10.8pt, style=Bold")]
        public global::System.Drawing.Font labelFont {
            get {
                return ((global::System.Drawing.Font)(this["labelFont"]));
            }
            set {
                this["labelFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman, 10.8pt")]
        public global::System.Drawing.Font chuFont {
            get {
                return ((global::System.Drawing.Font)(this["chuFont"]));
            }
            set {
                this["chuFont"] = value;
            }
        }
    }
}
